import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { Hero, Message } from "../components/Hero";
import CardList from "../features/card/CardList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>interaction app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Message />
        <div className="container mx-auto px-4">
          <section className="my-8">
            <CardList />
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
